### ISSUE TITLE
Improove quality

### ISSUE THREAD

**Issue by burymm** [nemascha/linkcreator#2]
- [x] 2.1 Добавить подтверждение при нажатии удалить все ссылки
- [x] 2.2 исправить баг https://www.screencast.com/t/m2tOrCgmsm. Добавить несколько ссылок, потом еще раз нажать добавить несколько ссылок.
- [x] 2.3 все ссылки должны иметь уникальное название не должно быть двух ссылок с одинаковым именем.
- [x] 2.4 кнопка удалить все ссылки должна быть всегда. Нужно такое поведение, когда ссылок нет - она скрыта, когда ссылки есть она появляется. Каждый раз создавать не нужно. 
- [x] 2.5  негласное соглашение все классы и ид-шки в html пишут используя тире quantity_input -> quantity-input а в js camelCase.
- [x] 2.6 newLinkContainer - нужно закэшировать. Т.е. получить ссылку при инициализации приложения а остальные разы, только обращаться. То же и с кнопкой "удалить все ссылки".
- [x] 2.7 можно обернуть это все в какой-то контейнер и тогда нужно следить только за контейнером, а не за 2-мя элементами. Это к тому, что количество внутренних элементов может вырасти. 
> remLinkButton.addEventListener('click',
> function removeLink () {
>			newLink.remove();
>			remLinkButton.remove();
>		});

- [x] 2.8 Нужно удалить контейнер, а  не только ссылку, потому что после нескольких циклов, остается пустое место.
- [x] Номера ссылок идут через 1. А должны по порядку.

**Comment by nemascha** [comment]
>исправить баг https://www.screencast.com/t/m2tOrCgmsm. Добавить несколько ссылок, потом еще раз нажать добавить несколько ссылок.
Я правильно понимаю, что каждый раз,когда я нажимаю на кнопку, ссылки должны добавляться со следующим номером, т.е. не ссылка 1, 1,1, а 1, 2, 3 и т.д?
>все ссылки должны иметь уникальное название не должно быть двух ссылок с одинаковым именем.
у меня так и есть. к id добавляется i.
> можно обернуть это все в какой-то контейнер
Ссылку и кнопку в отдельный div, который будет в основном div-e?

**Comment by burymm** [comment]
Укажи несколько ссылок, например 5 нажми создать. Кнопка удалить все снизу, нажимаешь создать еще раз кнопка уже сверху.

**Comment by burymm** [comment]
Про ссылки должны быть 1, 2, 3, 4, 5, 6, скажем удаляем 5 и 4. Я нажимаю создать еще 3 ссылки у них имя должно быть либо 4, 5, 7 или 7, 8, 9 как решишь.
а у тебя будет 1, 2. 3 и таких имен будет по 2. А если еще раз нажать, то еще раз добавятся.

**Comment by burymm** [comment]
Добавил пару комментариев к коммиту.
